name: صهقثلعشقی

on:
  workflow_dispatch

jobs:
  deploy-simple-proxy:
    runs-on: ubuntu-latest
    steps:
    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 socat

    - name: Start simple SOCKS proxy
      run: |
        # Start a simple Python SOCKS server
        python3 -m http.server 8080 > /tmp/http.log 2>&1 &
        
        # Start socat as TCP proxy
        socat TCP-LISTEN:9090,fork TCP:127.0.0.1:8080 > /tmp/socat.log 2>&1 &
        
        echo "PROXY_PORT=9090" >> $GITHUB_ENV
        sleep 3

    - name: Setup Ngrok
      run: |
        curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz | tar xz -C /tmp/
        chmod +x /tmp/ngrok
        /tmp/ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        /tmp/ngrok tcp 9090 > /tmp/ngrok.log 2>&1 &
        sleep 10

    - name: Get connection info
      run: |
        TUNNEL_INFO=$(curl -s http://localhost:4040/api/tunnels || echo "{}")
        if echo "$TUNNEL_INFO" | grep -q 'tcp://'; then
          TUNNEL_URL=$(echo "$TUNNEL_INFO" | grep -o 'tcp://[^"]*' | head -1)
          SERVER_IP=$(echo "$TUNNEL_URL" | cut -d':' -f2 | sed 's#//##')
          SERVER_PORT=$(echo "$TUNNEL_URL" | cut -d':' -f3)
        else
          SERVER_IP="0.tcp.ngrok.io"
          SERVER_PORT="9090"
        fi
        
        echo "SERVER_IP=$SERVER_IP" >> $GITHUB_ENV
        echo "SERVER_PORT=$SERVER_PORT" >> $GITHUB_ENV

    - name: Display info
      run: |
        echo "=========================================="
        echo "🚀 Simple Proxy Server Ready!"
        echo "=========================================="
        echo "Server: ${{ env.SERVER_IP }}"
        echo "Port: ${{ env.SERVER_PORT }}"
        echo "Type: TCP Proxy"
        echo ""
        echo "Usage: Connect to ${{ env.SERVER_IP }}:${{ env.SERVER_PORT }}"
        echo "=========================================="

    - name: Keep alive
      run: |
        echo "🟢 Server running for 6 hours..."
        sleep 21600
